### ISSUE TITLE
Undefined property: Proxy::getMethods- payment checkout

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#277] opened 2024-02-03 23:34 UTC
https://github.com/opencart/opencart-3/blob/main/upload/catalog/model/checkout/payment_method.php#L26-L27

**Comment by TheCartpenter** [comment] 2024-02-03 23:46
OC 4 also has it. May be each methods must be created accordingly even though it must be known if the method is callable or not.

**Comment by condor2** [comment] 2024-02-03 23:58
Possible is another issue because shipping method use "same" code

`if (is_callable([$this->{'model_extension_shipping_' . $result['code']}, 'getQuote'])) {`

**Comment by TheCartpenter** [comment] 2024-02-04 00:07
I did wondered when adding the lookup. Possible conflicts of instantiation.

**Comment by TheCartpenter** [comment] 2024-02-04 23:51
Dumped each callable magic methods into variables: https://github.com/opencart/opencart-3/commit/f6535fe3c67005e78a1922a9c08451fb26ab3598 .

**Comment by TheCartpenter** [comment] 2024-02-05 00:23
Tested with: https://github.com/opencart/opencart-3/commit/6f92c76b0aaff9c44e00ff2a8ff090a2eebfeb25 , it looks like even though the ```is_callable``` would look for a variable instead of using a direct condition, it will still fail to find the targeted method name if it doesn't exist from its condition.

@AJenbo: The solution provided here: https://github.com/opencart/opencart/blob/master/upload/catalog/controller/cron/subscription.php#L361 would, therefore, not provide any difference in regard to a variable vs. direct condition with a ```is_callable``` function.

**Comment by AJenbo** [comment] 2024-02-05 02:58
I didn't write that code:

![image](https://github.com/opencart/opencart-3/assets/204594/3c071540-22ff-4149-81ff-523c97b4d9f0)

Probably the reason to put it in a variable would be to have shorter lines but idk.

is_callable() is needed when the object isn't well defined and the existence of the method can only be determined at runtime. Since OC refrains from using interfaces a lot of it's code is not well defined.

**Comment by condor2** [comment] 2024-02-05 08:02
Theoretical 

`$callable = [$this->{'model_extension_payment_' . $result['code']}, 'getMethods'];`

is like

`$callable = [$this->{'model_extension_payment_' . cod}, 'getMethods'];`

and **getMethods** is not read from all payments model?

But in model I don't see where is write **getMethods**
https://github.com/opencart/opencart-3/blob/main/upload/catalog/model/extension/payment/cod.php#L15

**Comment by AJenbo** [comment] 2024-02-05 08:12
First problem, line 361 uses this:
`{'model_extension_' . $extension_info['extension'] . '_payment_' . $extension_info['code']}`
But line 365 calls this:
`{'model_extension_' . $order_data['payment_method']['extension'] . '_payment_' . $order_data['payment_method']['code']}`

The first one is done to check that the second won't fail so they need to be identical.

Next issue is that the analyzer can't know that building the name twice will give the same result, so use `$callable` twice instead of building the name twice.

```php
if (is_callable($callable)) {
	// Process payment
	$response_info = $callable($this->customer->getId(), $this->session->data['order_id'], $order_info['total'], $order_data['payment_method']['code']);
```

**Comment by TheCartpenter** [comment] 2024-02-05 11:40
> First problem, line 361 uses this: `{'model_extension_' . $extension_info['extension'] . '_payment_' . $extension_info['code']}` But line 365 calls this: `{'model_extension_' . $order_data['payment_method']['extension'] . '_payment_' . $order_data['payment_method']['code']}`
> 
> The first one is done to check that the second won't fail so they need to be identical.
> 
> Next issue is that the analyzer can't know that building the name twice will give the same result, so use `$callable` twice instead of building the name twice.
> 
> ```
> if (is_callable($callable)) {
> 	// Process payment
> 	$response_info = $callable($this->customer->getId(), $this->session->data['order_id'], $order_info['total'], $order_data['payment_method']['code']);
> ```

Ok, will take care of that. As for OC 4, however, the same way should be used with the ```$callable``` since an IF statement is used but then recalls the models dynamically which means the analyzer may not like it any better on a higher diagnostic level than it may not already like it on a lower level from this repository. If one is concerned about using a variable while OCMod has been re-integrated in OC 4 as opposed to constantly throwing errors in PHPStan while using a variable may both solve these errors, the probability that users will be able to make those changes with XML in the future are probably going to be higher on anyhow, therefore, ```$callable``` should also be considered in OC 4.

**Comment by AJenbo** [comment] 2024-02-05 12:43
OC 3 has class name collisions because it does not use namespaces which makes it unable to pass level 2.

OC 4 has namespaces. But is unable to pass level 7 because it isn't clear if it's loading a `Model` from the `Admin` or `Catalog` namespace when you access something like `$this->model_sale_order->getOrder();`.

**Comment by TheCartpenter** [comment] 2024-02-05 13:49
Should be fixed, now: https://github.com/opencart/opencart-3/commit/c03237f9e4de8bb6ce12b2f9ff785be2371c6801

**Closed by TheCartpenter** 2024-02-05 13:49 UTC
Labels: Needs testing

**Comment by condor2** [comment] 2024-02-05 14:07
@TheCartpenter  from where **getMethods** is taken?

`$callable = [$this->{'model_extension_payment_' . $result['code']}, 'getMethods'];`

Is not like this?
Load the file.... **model_extension_payment_cod** and read **getMethods** function? But in all payments models there is no **getMethods** fucntion

On the shipping_method you have used **'getQuote'** but funtion exist in all shipping model.

**Comment by TheCartpenter** [comment] 2024-02-05 14:33
That is why I am using ```is_callable``` so to know if the ```getMethods()``` does exist prior to use it. As for the singular vs. the plural method conventional names, I am not done, yet. Work still needs to be done on that side.

**Comment by TheCartpenter** [comment] 2024-02-05 14:46
> OC 3 has class name collisions because it does not use namespaces which makes it unable to pass level 2.
> 
> OC 4 has namespaces. But is unable to pass level 7 because it isn't clear if it's loading a `Model` from the `Admin` or `Catalog` namespace when you access something like `$this->model_sale_order->getOrder();`.

Will the ```$callable``` also respond to the shipping quotes (```$quote```) by using ```referenced``` variables like ```$total_data``` and ```$total``` also when putting the ```getTotal()``` ?

**Comment by condor2** [comment] 2024-02-05 14:58
I made a PR https://github.com/opencart/opencart-3/pull/283/files , to replace getMethod with getMethods , but on checkout doesn't show payment method name :)
![no_name_payment](https://github.com/opencart/opencart-3/assets/14251939/03782c33-4c9a-44d2-a585-b77cf5cf1fd2)

**Comment by TheCartpenter** [comment] 2024-02-05 15:19
That's because the payment_method and shipping_method now takes the lead for the $callable. Therefore, each ```$callable``` need to be replaced to the same calls as OC 4 from controller/checkout/payment_method and controller/checkout/shipping_method from now on.

**Comment by TheCartpenter** [comment] 2024-02-05 15:22
Take note that the extension/extension folder using ```$callable``` is not reflected with the suggested change above.

**Comment by AJenbo** [comment] 2024-02-05 15:23
From what I see you created the callable using the array syntax so it will go through the `Proxy::__call()` method which is not made to handle variables by reference. But if you want to avoid that you could simply create the variable in another way, like:

```php
if (isset($this->{'model_' . $blabla}->getMethods)) {
    $callable = $this->{'model_' . $blabla}->getMethods;
```

**Comment by TheCartpenter** [comment] 2024-02-05 15:32
> From what I see you created the callable using the array syntax so it will go through the `Proxy::__call()` method which is not made to handle variables by reference. But if you want to avoid that you could simply create the variable in another way, like:
> 
> ```
> if (isset($this->{'model_' . $blabla}->getMethods)) {
>     $callable = $this->{'model_' . $blabla}->getMethods;
> ```

I was hoping to avoid the use of ```isset``` and ```property_exists``` for those calls. Would bringing those specific calls to their previous state still create a conflict with the totals whenever there are referenced variables in-place?

**Comment by AJenbo** [comment] 2024-02-05 15:50
What previous state?

**Comment by TheCartpenter** [comment] 2024-02-05 18:33
> What previous state?

Reverted totals with original calls: https://github.com/opencart/opencart-3/commit/656aba73ea3fbdb7c2a41738950009af30dff5f2

**Comment by AJenbo** [comment] 2024-02-05 18:38
Yes, you need to do the following if you want to avoid the magic __call():

```php
$callable = $this->{'model_extension_total_' . $result['code']}->getTotal;
$callable($total_data);
```

**Comment by TheCartpenter** [comment] 2024-02-05 18:50
> Yes, you need to do the following if you want to avoid the magic __call():
> 
> ```
> $callable = $this->{'model_extension_total_' . $result['code']}->getTotal;
> $callable($total_data);
> ```

Would that also prevent conflicts between the ```getTotal``` methods during the same instantiation?

**Comment by AJenbo** [comment] 2024-02-05 18:59
What do you mean by conflict?

**Comment by TheCartpenter** [comment] 2024-02-05 19:18
> What do you mean by conflict?

https://github.com/opencart/opencart-3/issues/277#issuecomment-1925490909

By following this, using the same scenarios from your above solution, is there a possible scenario where the comment from @condor2 may be reproduced with ```$callable($total_data)``` ?

**Comment by TheCartpenter** [comment] 2024-02-05 20:12
I'll leave it to the original calls, for now. Order totals seem to work with the referenced variables.
