### ISSUE TITLE
Error during checkout with new customer

### ISSUE THREAD

**Issue by opencartcomvn** [opencart/opencart-3#147] opened 2022-11-10 03:42 UTC
![1](https://user-images.githubusercontent.com/82214791/200995447-e4219764-e053-4710-9ff7-8864bf6432c8.png)
![2](https://user-images.githubusercontent.com/82214791/200995452-655d4ad0-8c80-4dc8-b732-1ea12516214f.png)
![3](https://user-images.githubusercontent.com/82214791/200995455-7518eb1f-6cb3-4643-96b6-1b262b9df056.png)

Error with 
`PHP Warning:  Undefined array key "trial_remaining" in E:\Ampps\www\3xx\system\library\cart\cart.php on line 230`

![4](https://user-images.githubusercontent.com/82214791/200995456-1745b266-49b1-4c81-9227-b2ccc921ddaf.png)

**Comment by opencartcomvn** [comment] 2022-11-10 03:51
Error when move storage to other path

Apache 2.4.54
Mysql 8.0.31
php 8.1.12

**Comment by TheCartpenter** [comment] 2022-11-10 16:07
The trial_remaining error issue has now been solved. However, I will take a look at the other issues reported on the screenshots.



> Error when move storage to other path
> 
> Apache 2.4.54 Mysql 8.0.31 php 8.1.12

Need more information on this one. Doesn't mention anything specific.

**Comment by opencartcomvn** [comment] 2022-11-11 00:28
> The trial_remaining error issue has now been solved. However, I will take a look at the other issues reported on the screenshots.
> 
> > Error when move storage to other path
> > Apache 2.4.54 Mysql 8.0.31 php 8.1.12
> 
> Need more information on this one. Doesn't mention anything specific.

Admin and website blank page because cannot access storage

![Screenshot from 2022-11-11 07-18-13](https://user-images.githubusercontent.com/82214791/201234035-50170c48-71f9-4d54-99f8-a45b1ec9b858.png)
![Screenshot from 2022-11-11 07-20-12](https://user-images.githubusercontent.com/82214791/201234051-b537980e-8e0d-4081-8777-6faf839277f0.png)
![Screenshot from 2022-11-11 07-25-30](https://user-images.githubusercontent.com/82214791/201234056-05ca3821-57f7-42d9-88ac-b8773ef0ca51.png)
![Screenshot from 2022-11-11 07-25-43](https://user-images.githubusercontent.com/82214791/201234061-7c39e769-a121-486a-ab30-48626c5381cd.png)

**Comment by TheCartpenter** [comment] 2022-11-11 01:42
The automated move out of the storage folder from the admin is a long time reported issue. In OC 4, this has been rectified. However, in OC-3, it is on-going since it uses an older method to move the storage sub-folders and files. Also make sure your target storage folder has the proper CHMOD permissions and set recursively to 0755. As for your files, they need to remain on 0644.

It is stated on the OC forum that dedicated servers cannot reproduce those issues while moving the folders. It's only hosting packages that are under. Therefore, manual move process might be required if not using a dedicated server.

**Comment by opencartcomvn** [comment] 2022-11-11 01:49
> The automated move out of the storage folder from the admin is a long time reported issue. In OC 4, this has been rectified. However, in OC-3, it is on-going since it uses an older method to move the storage sub-folders and files. Also make sure your target storage folder has the proper CHMOD permissions and set recursively to 0755. As for your files, they need to remain on 0644.
> 
> It is stated on the OC forum that dedicated servers cannot reproduce those issues while moving the folders. It's only hosting packages that are under. Therefore, manual move process might be required if not using a dedicated server.

Hi,
I'm try install on windows with ampps
https://ampps.com/downloads/
After move storage automatic
The same problem.
But with old version 3.0.3.8 and 4.0.1.1 and 4.0.2.0 it ok work perfect.

**Comment by TheCartpenter** [comment] 2022-11-11 03:18
Checkout errors needs to be looked at, first. Then, I'll see why these logs are showing after using common/security. As I said, OC 4.x releases sure fixes this issue because the move process for the storage folder has been rewritten. As for OC v3,0,3,8, it still uses the old vendors packages in the storage while OC-3, this branch, uses a smaller portion of the OC-4 vendors.

**Comment by TheCartpenter** [comment] 2022-11-12 19:27
This issue has been reported before on previous OC releases. This is cause by site redirection issue when filling up a new delivery address. The ```$this->session->data['shipping_address']``` is not yet found by the browser until it redirects or when we refresh the page. Maybe it used to work in the past but now it seem that the ```shipping_address``` can no longer be used in the same event before redirecting. Will have to look into that.

**Comment by TheCartpenter** [comment] 2022-11-12 21:34
It looks like this issue might be related with this one in regard to the Geo Zone settings that may lead to this error message. See this solution by configuring the Geo Zones: https://forum.opencart.com/viewtopic.php?t=45360#p228496 .

**Comment by TheCartpenter** [comment] 2022-11-13 01:25
Re-opening. Found the issue. The default field cannot be set to a value of 1 in OC-3. Only in OC-4. However, OC-4 did not had this field ready either from OC 3.x releases. This is a major incident. Pull request submitted and re-opening this commit.

**Comment by TheCartpenter** [comment] 2022-11-13 01:54
Should be fixed now.

**Closed by TheCartpenter** 2022-11-13 01:54 UTC
